name: C/C++ CI CL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildCL:

    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      
    - name: Compile .c file
      run: cl huawei_bootloader_unlocker.c /out:huawei_bootloader_unlocker.exe
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: huawei_bootloader_unlocker
        path: ./huawei_bootloader_unlocker.exe
      
